name = "dsgame"
main = "worker.js"
compatibility_date = "2026-09-04"

[[kv_namespaces]]
binding = "DEVICES"
id = "ff9eaa1035a842f1a7a287fa56153adf"

[vars]
GITHUB_RAW_KEYS = "https://raw.githubusercontent.com/hieuvlog2001-creator/DSGAME/main/keys.json"
